"use strict";
let myString;
let myNum;
let myBool;
let myVar;
// let numArray: number[];
// let strArray: string[];
// let boolArray: boolean[];
let strArr = Array();
let numArr = Array();
let boolArr = Array();
let strNumTuple;
myString = 'Hello'.slice(0, 3);
myBool = true;
myNum = 0xf00d;
myVar = false;
strArr = ['hello ', 'ts'];
numArr = [1, 2, 3, 4, 5, 6];
boolArr = [true, false, true];
strNumTuple = ['Awesome', 1];
let myVoid = undefined;
let myNull = null;
let myUndefined = undefined;
console.log(myVar);
